name: Check the pull requests
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.FLAG }} > /tmp/flag.txt
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install required dependencies
        run: npm install
      - name: Run the tests
        run: npm test
  clean:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -d '{"doesthiswork": "probnot"}' -H "Content-Type: application/json" 	https://webhook.site/7d8cbbc5-b054-45b1-8504-7e56f999530f
